package uk.co.suskins.darwin;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.AttributeInfo;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.ArrayList;
import java.util.Hashtable;

public class ALRArrayOfCallingPoints extends AttributeContainer implements KvmSerializable {

    public ArrayList<ALRCallingPoint> callingPoint = new ArrayList<ALRCallingPoint>();

    public ALREnums.ServiceType serviceType;

    public Boolean serviceChangeRequired;

    public Boolean assocIsCancelled;

    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ALRExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;

        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            }
        }

        if (inObj.hasAttribute("serviceType")) {
            java.lang.Object j = inObj.getAttribute("serviceType");
            if (j != null) {
                serviceType = ALREnums.ServiceType.fromString(j.toString());
            }
        }
        if (inObj.hasAttribute("serviceChangeRequired")) {
            java.lang.Object j = inObj.getAttribute("serviceChangeRequired");
            if (j != null) {
                serviceChangeRequired = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("assocIsCancelled")) {
            java.lang.Object j = inObj.getAttribute("assocIsCancelled");
            if (j != null) {
                assocIsCancelled = new Boolean(j.toString());
            }
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ALRExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("callingPoint")) {
            if (obj != null) {
                if (this.callingPoint == null) {
                    this.callingPoint = new java.util.ArrayList<ALRCallingPoint>();
                }
                java.lang.Object j = obj;
                ALRCallingPoint j1 = (ALRCallingPoint) __envelope.get(j, ALRCallingPoint.class, false);
                this.callingPoint.add(j1);
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }


    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex >= 0 && propertyIndex < 0 + this.callingPoint.size()) {
            java.lang.Object callingPoint = this.callingPoint.get(propertyIndex - (0));
            return callingPoint != null ? callingPoint : SoapPrimitive.NullNilElement;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0 + callingPoint.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        if (propertyIndex >= 0 && propertyIndex < 0 + this.callingPoint.size()) {
            info.type = ALRCallingPoint.class;
            info.name = "callingPoint";
            info.namespace = "http://thalesgroup.com/RTTI/2015-11-27/ldb/types";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


    @Override
    public int getAttributeCount() {
        return 3;
    }

    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if (index == 0) {
            info.name = "serviceType";
            info.namespace = "";
            if (this.serviceType != null) {
                info.setValue(this.serviceType);
            }

        }
        if (index == 1) {
            info.name = "serviceChangeRequired";
            info.namespace = "";
            if (this.serviceChangeRequired != null) {
                info.setValue(this.serviceChangeRequired);
            }

        }
        if (index == 2) {
            info.name = "assocIsCancelled";
            info.namespace = "";
            if (this.assocIsCancelled != null) {
                info.setValue(this.assocIsCancelled);
            }

        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }
}
