package uk.co.suskins.darwin;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class ALRCallingPoint_1 extends AttributeContainer implements KvmSerializable {

    public String locationName;

    public String crs;

    public String st;

    public String et;

    public String at;

    public Boolean isCancelled;

    public Integer length;

    public Boolean detachFront;

    public ALRFormationData formation;

    public ALRArrayOfAdhocAlert adhocAlerts;

    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ALRExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;

        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                if (!loadProperty(info, soapObject, __envelope)) {
                }
            }
        }


    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ALRExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("locationName")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.locationName = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.locationName = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("crs")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.crs = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.crs = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("st")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.st = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.st = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("et")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.et = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.et = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("at")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.at = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.at = (String) obj;
                }
            }
            return true;
        }
        if (info.name.equals("isCancelled")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.isCancelled = new Boolean(j.toString());
                    }
                } else if (obj instanceof Boolean) {
                    this.isCancelled = (Boolean) obj;
                }
            }
            return true;
        }
        if (info.name.equals("length")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.length = Integer.parseInt(j.toString());
                    }
                } else if (obj instanceof Integer) {
                    this.length = (Integer) obj;
                }
            }
            return true;
        }
        if (info.name.equals("detachFront")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.detachFront = new Boolean(j.toString());
                    }
                } else if (obj instanceof Boolean) {
                    this.detachFront = (Boolean) obj;
                }
            }
            return true;
        }
        if (info.name.equals("formation")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.formation = (ALRFormationData) __envelope.get(j, ALRFormationData.class, false);
            }
            return true;
        }
        if (info.name.equals("adhocAlerts")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.adhocAlerts = (ALRArrayOfAdhocAlert) __envelope.get(j, ALRArrayOfAdhocAlert.class, false);
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }


    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex == 0) {
            return locationName;
        }
        if (propertyIndex == 1) {
            return crs;
        }
        if (propertyIndex == 2) {
            return this.st != null ? this.st : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 3) {
            return this.et != null ? this.et : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 4) {
            return this.at != null ? this.at : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 5) {
            return this.isCancelled != null ? this.isCancelled : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 6) {
            return this.length != null ? this.length : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 7) {
            return this.detachFront != null ? this.detachFront : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 8) {
            return this.formation != null ? this.formation : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == 9) {
            return this.adhocAlerts != null ? this.adhocAlerts : SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 10;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        if (propertyIndex == 0) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "locationName";
            info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/types";
        }
        if (propertyIndex == 1) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "crs";
            info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/types";
        }
        if (propertyIndex == 2) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "st";
            info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/types";
        }
        if (propertyIndex == 3) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "et";
            info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/types";
        }
        if (propertyIndex == 4) {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "at";
            info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/types";
        }
        if (propertyIndex == 5) {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "isCancelled";
            info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/types";
        }
        if (propertyIndex == 6) {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "length";
            info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/types";
        }
        if (propertyIndex == 7) {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "detachFront";
            info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/types";
        }
        if (propertyIndex == 8) {
            info.type = ALRFormationData.class;
            info.name = "formation";
            info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/types";
        }
        if (propertyIndex == 9) {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "adhocAlerts";
            info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/types";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


}
