package uk.co.suskins.darwin;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


public class ALREnums {

    public enum FilterType {

        to(0),

        from(1);

        private int code;

        FilterType(int code) {
            this.code = code;
        }

        public static FilterType fromString(String str) {
            if (str.equals("to"))
                return to;
            if (str.equals("from"))
                return from;
            return null;
        }

        public int getCode() {
            return code;
        }
    }

    public enum ServiceType {

        train(0),

        bus(1),

        ferry(2);

        private int code;

        ServiceType(int code) {
            this.code = code;
        }

        public static ServiceType fromString(String str) {
            if (str.equals("train"))
                return train;
            if (str.equals("bus"))
                return bus;
            if (str.equals("ferry"))
                return ferry;
            return null;
        }

        public int getCode() {
            return code;
        }
    }

    public enum ToiletStatus {

        Unknown(0),

        InService(1),

        NotInService(2);

        private int code;

        ToiletStatus(int code) {
            this.code = code;
        }

        public static ToiletStatus fromString(String str) {
            if (str.equals("Unknown"))
                return Unknown;
            if (str.equals("InService"))
                return InService;
            if (str.equals("NotInService"))
                return NotInService;
            return null;
        }

        public int getCode() {
            return code;
        }
    }

}