package uk.co.suskins.darwin;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


public interface ALRIServiceEvents {
    void Starting();

    void Completed(ALROperationResult result);
}
