package uk.co.suskins.darwin;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.kxml2.kdom.Element;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class ALRLDBServiceSoap {
    public List<HeaderProperty> httpHeaders = new ArrayList<HeaderProperty>();
    public boolean enableLogging;
    String url = "https://lite.realtime.nationalrail.co.uk/OpenLDBWS/ldb11.asmx";
    int timeOut = 60000;
    ALRIServiceEvents callback;

    public ALRLDBServiceSoap() {
    }

    public ALRLDBServiceSoap(ALRIServiceEvents callback) {
        this.callback = callback;
    }

    public ALRLDBServiceSoap(ALRIServiceEvents callback, String url) {
        this.callback = callback;
        this.url = url;
    }

    public ALRLDBServiceSoap(ALRIServiceEvents callback, String url, int timeOut) {
        this.callback = callback;
        this.url = url;
        this.timeOut = timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport() {
        try {
            java.net.URI uri = new java.net.URI(url);
            if (uri.getScheme().equalsIgnoreCase("https")) {
                int port = uri.getPort() > 0 ? uri.getPort() : 443;
                return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            } else {
                return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url, timeOut);
            }

        } catch (java.net.URISyntaxException e) {
        }
        return null;
    }

    protected ALRExtendedSoapSerializationEnvelope createEnvelope() {
        ALRExtendedSoapSerializationEnvelope envelope = new ALRExtendedSoapSerializationEnvelope(ALRExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }

    protected java.util.List sendRequest(String methodName, ALRExtendedSoapSerializationEnvelope envelope, org.ksoap2.transport.Transport transport, com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws java.lang.Exception {
        if (transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE) {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE) transport).call(methodName, envelope, httpHeaders, null, profile);
        } else {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE) transport).call(methodName, envelope, httpHeaders, null, profile);
        }
    }

    java.lang.Object getResult(java.lang.Class destObj, java.lang.Object source, String resultName, ALRExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception {
        if (source == null) {
            return null;
        }
        if (source instanceof SoapPrimitive) {
            SoapPrimitive soap = (SoapPrimitive) source;
            if (soap.getName().equals(resultName)) {
                java.lang.Object instance = __envelope.get(source, destObj, false);
                return instance;
            }
        } else {
            SoapObject soap = (SoapObject) source;
            if (soap.hasProperty(resultName)) {
                java.lang.Object j = soap.getProperty(resultName);
                if (j == null) {
                    return null;
                }
                java.lang.Object instance = __envelope.get(j, destObj, false);
                return instance;
            } else if (soap.getName().equals(resultName)) {
                java.lang.Object instance = __envelope.get(source, destObj, false);
                return instance;
            }
        }

        return null;
    }

    public ALRStationBoard_2 GetDepartureBoard(final Integer numRows, final String crs, final String filterCrs, final ALREnums.FilterType filterType, final Integer timeOffset, final Integer timeWindow, final ALRAccessToken AccessToken) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ALRStationBoard_2) execute(new ALRIWcfMethod() {
            @Override
            public ALRExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ALRExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(ALRHelper.convertToHeader(AccessToken != null ? AccessToken : SoapPrimitive.NullNilElement, "http://thalesgroup.com/RTTI/2013-11-28/Token/types", "AccessToken"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://thalesgroup.com/RTTI/2017-10-01/ldb/", "GetDepartureBoardRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "numRows";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(numRows);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "crs";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(crs);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "filterCrs";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(filterCrs != null ? filterCrs : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "filterType";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(filterType != null ? filterType.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "timeOffset";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeOffset != null ? timeOffset : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "timeWindow";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeWindow != null ? timeWindow : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ALRExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(ALRStationBoard_2.class, __result, "GetStationBoardResult", __envelope);
            }
        }, "http://thalesgroup.com/RTTI/2012-01-13/ldb/GetDepartureBoard", __profile);
    }

    public android.os.AsyncTask<Void, Void, ALROperationResult<ALRStationBoard_2>> GetDepartureBoardAsync(final Integer numRows, final String crs, final String filterCrs, final ALREnums.FilterType filterType, final Integer timeOffset, final Integer timeWindow, final ALRAccessToken AccessToken) {
        return executeAsync(new ALRFunctions.IFunc<ALRStationBoard_2>() {
            public ALRStationBoard_2 Func() throws java.lang.Exception {
                return GetDepartureBoard(numRows, crs, filterCrs, filterType, timeOffset, timeWindow, AccessToken);
            }
        }, "GetDepartureBoard");
    }

    public ALRStationBoard_2 GetArrivalBoard(final Integer numRows, final String crs, final String filterCrs, final ALREnums.FilterType filterType, final Integer timeOffset, final Integer timeWindow, final ALRAccessToken AccessToken) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ALRStationBoard_2) execute(new ALRIWcfMethod() {
            @Override
            public ALRExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ALRExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(ALRHelper.convertToHeader(AccessToken != null ? AccessToken : SoapPrimitive.NullNilElement, "http://thalesgroup.com/RTTI/2013-11-28/Token/types", "AccessToken"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://thalesgroup.com/RTTI/2017-10-01/ldb/", "GetArrivalBoardRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "numRows";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(numRows);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "crs";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(crs);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "filterCrs";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(filterCrs != null ? filterCrs : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "filterType";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(filterType != null ? filterType.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "timeOffset";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeOffset != null ? timeOffset : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "timeWindow";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeWindow != null ? timeWindow : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ALRExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(ALRStationBoard_2.class, __result, "GetStationBoardResult", __envelope);
            }
        }, "http://thalesgroup.com/RTTI/2012-01-13/ldb/GetArrivalBoard", __profile);
    }

    public android.os.AsyncTask<Void, Void, ALROperationResult<ALRStationBoard_2>> GetArrivalBoardAsync(final Integer numRows, final String crs, final String filterCrs, final ALREnums.FilterType filterType, final Integer timeOffset, final Integer timeWindow, final ALRAccessToken AccessToken) {
        return executeAsync(new ALRFunctions.IFunc<ALRStationBoard_2>() {
            public ALRStationBoard_2 Func() throws java.lang.Exception {
                return GetArrivalBoard(numRows, crs, filterCrs, filterType, timeOffset, timeWindow, AccessToken);
            }
        }, "GetArrivalBoard");
    }

    public ALRStationBoard_2 GetArrivalDepartureBoard(final Integer numRows, final String crs, final String filterCrs, final ALREnums.FilterType filterType, final Integer timeOffset, final Integer timeWindow, final ALRAccessToken AccessToken) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ALRStationBoard_2) execute(new ALRIWcfMethod() {
            @Override
            public ALRExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ALRExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(ALRHelper.convertToHeader(AccessToken != null ? AccessToken : SoapPrimitive.NullNilElement, "http://thalesgroup.com/RTTI/2013-11-28/Token/types", "AccessToken"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://thalesgroup.com/RTTI/2017-10-01/ldb/", "GetArrivalDepartureBoardRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "numRows";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(numRows);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "crs";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(crs);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "filterCrs";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(filterCrs != null ? filterCrs : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "filterType";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(filterType != null ? filterType.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "timeOffset";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeOffset != null ? timeOffset : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "timeWindow";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeWindow != null ? timeWindow : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ALRExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(ALRStationBoard_2.class, __result, "GetStationBoardResult", __envelope);
            }
        }, "http://thalesgroup.com/RTTI/2012-01-13/ldb/GetArrivalDepartureBoard", __profile);
    }

    public android.os.AsyncTask<Void, Void, ALROperationResult<ALRStationBoard_2>> GetArrivalDepartureBoardAsync(final Integer numRows, final String crs, final String filterCrs, final ALREnums.FilterType filterType, final Integer timeOffset, final Integer timeWindow, final ALRAccessToken AccessToken) {
        return executeAsync(new ALRFunctions.IFunc<ALRStationBoard_2>() {
            public ALRStationBoard_2 Func() throws java.lang.Exception {
                return GetArrivalDepartureBoard(numRows, crs, filterCrs, filterType, timeOffset, timeWindow, AccessToken);
            }
        }, "GetArrivalDepartureBoard");
    }

    public ALRServiceDetails GetServiceDetails(final String serviceID, final ALRAccessToken AccessToken) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ALRServiceDetails) execute(new ALRIWcfMethod() {
            @Override
            public ALRExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ALRExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(ALRHelper.convertToHeader(AccessToken != null ? AccessToken : SoapPrimitive.NullNilElement, "http://thalesgroup.com/RTTI/2013-11-28/Token/types", "AccessToken"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://thalesgroup.com/RTTI/2017-10-01/ldb/", "GetServiceDetailsRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "serviceID";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(serviceID);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ALRExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(ALRServiceDetails.class, __result, "GetServiceDetailsResult", __envelope);
            }
        }, "http://thalesgroup.com/RTTI/2012-01-13/ldb/GetServiceDetails", __profile);
    }

    public android.os.AsyncTask<Void, Void, ALROperationResult<ALRServiceDetails>> GetServiceDetailsAsync(final String serviceID, final ALRAccessToken AccessToken) {
        return executeAsync(new ALRFunctions.IFunc<ALRServiceDetails>() {
            public ALRServiceDetails Func() throws java.lang.Exception {
                return GetServiceDetails(serviceID, AccessToken);
            }
        }, "GetServiceDetails");
    }

    public ALRStationBoardWithDetails_2 GetDepBoardWithDetails(final Integer numRows, final String crs, final String filterCrs, final ALREnums.FilterType filterType, final Integer timeOffset, final Integer timeWindow, final ALRAccessToken AccessToken) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ALRStationBoardWithDetails_2) execute(new ALRIWcfMethod() {
            @Override
            public ALRExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ALRExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(ALRHelper.convertToHeader(AccessToken != null ? AccessToken : SoapPrimitive.NullNilElement, "http://thalesgroup.com/RTTI/2013-11-28/Token/types", "AccessToken"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://thalesgroup.com/RTTI/2017-10-01/ldb/", "GetDepBoardWithDetailsRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "numRows";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(numRows);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "crs";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(crs);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "filterCrs";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(filterCrs != null ? filterCrs : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "filterType";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(filterType != null ? filterType.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "timeOffset";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeOffset != null ? timeOffset : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "timeWindow";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeWindow != null ? timeWindow : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ALRExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(ALRStationBoardWithDetails_2.class, __result, "GetStationBoardResult", __envelope);
            }
        }, "http://thalesgroup.com/RTTI/2015-05-14/ldb/GetDepBoardWithDetails", __profile);
    }

    public android.os.AsyncTask<Void, Void, ALROperationResult<ALRStationBoardWithDetails_2>> GetDepBoardWithDetailsAsync(final Integer numRows, final String crs, final String filterCrs, final ALREnums.FilterType filterType, final Integer timeOffset, final Integer timeWindow, final ALRAccessToken AccessToken) {
        return executeAsync(new ALRFunctions.IFunc<ALRStationBoardWithDetails_2>() {
            public ALRStationBoardWithDetails_2 Func() throws java.lang.Exception {
                return GetDepBoardWithDetails(numRows, crs, filterCrs, filterType, timeOffset, timeWindow, AccessToken);
            }
        }, "GetDepBoardWithDetails");
    }

    public ALRStationBoardWithDetails_2 GetArrBoardWithDetails(final Integer numRows, final String crs, final String filterCrs, final ALREnums.FilterType filterType, final Integer timeOffset, final Integer timeWindow, final ALRAccessToken AccessToken) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ALRStationBoardWithDetails_2) execute(new ALRIWcfMethod() {
            @Override
            public ALRExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ALRExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList<org.kxml2.kdom.Element> __headers = null;
                if (__envelope.headerOut == null) {
                    __headers = new ArrayList<org.kxml2.kdom.Element>();
                } else {
                    __headers = new ArrayList<org.kxml2.kdom.Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(ALRHelper.convertToHeader(AccessToken != null ? AccessToken : SoapPrimitive.NullNilElement, "http://thalesgroup.com/RTTI/2013-11-28/Token/types", "AccessToken"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://thalesgroup.com/RTTI/2017-10-01/ldb/", "GetArrBoardWithDetailsRequest");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "numRows";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(numRows);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "crs";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(crs);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "filterCrs";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(filterCrs != null ? filterCrs : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "filterType";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(filterType != null ? filterType.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "timeOffset";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeOffset != null ? timeOffset : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/";
                __info.name = "timeWindow";
                __info.type = PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeWindow != null ? timeWindow : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ALRExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                return getResult(ALRStationBoardWithDetails_2.class, __result, "GetStationBoardResult", __envelope);
            }
        }, "http://thalesgroup.com/RTTI/2015-05-14/ldb/GetArrBoardWithDetails", __profile);
    }

    public android.os.AsyncTask<Void, Void, ALROperationResult<ALRStationBoardWithDetails_2>> GetArrBoardWithDetailsAsync(final Integer numRows, final String crs, final String filterCrs, final ALREnums.FilterType filterType, final Integer timeOffset, final Integer timeWindow, final ALRAccessToken AccessToken) {
        return executeAsync(new ALRFunctions.IFunc<ALRStationBoardWithDetails_2>() {
            public ALRStationBoardWithDetails_2 Func() throws java.lang.Exception {
                return GetArrBoardWithDetails(numRows, crs, filterCrs, filterType, timeOffset, timeWindow, AccessToken);
            }
        }, "GetArrBoardWithDetails");
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    public String GetArrDepBoardWithDetails(final String numRows, final String crs, final String filterCrs, final String filterType, final String timeOffset, final String timeWindow, final String AccessToken) throws java.lang.Exception {

        /*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    public android.os.AsyncTask<Void, Void, ALROperationResult<String>> GetArrDepBoardWithDetailsAsync(final String numRows, final String crs, final String filterCrs, final String filterType, final String timeOffset, final String timeWindow, final String AccessToken) {
        return executeAsync(new ALRFunctions.IFunc<String>() {
            public String Func() throws java.lang.Exception {
                return GetArrDepBoardWithDetails(numRows, crs, filterCrs, filterType, timeOffset, timeWindow, AccessToken);
            }
        }, "GetArrDepBoardWithDetails");
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    public String GetNextDepartures(final String crs, final String filterList, final String timeOffset, final String timeWindow, final String AccessToken) throws java.lang.Exception {

        /*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    public android.os.AsyncTask<Void, Void, ALROperationResult<String>> GetNextDeparturesAsync(final String crs, final String filterList, final String timeOffset, final String timeWindow, final String AccessToken) {
        return executeAsync(new ALRFunctions.IFunc<String>() {
            public String Func() throws java.lang.Exception {
                return GetNextDepartures(crs, filterList, timeOffset, timeWindow, AccessToken);
            }
        }, "GetNextDepartures");
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    public String GetNextDeparturesWithDetails(final String crs, final String filterList, final String timeOffset, final String timeWindow, final String AccessToken) throws java.lang.Exception {

        /*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    public android.os.AsyncTask<Void, Void, ALROperationResult<String>> GetNextDeparturesWithDetailsAsync(final String crs, final String filterList, final String timeOffset, final String timeWindow, final String AccessToken) {
        return executeAsync(new ALRFunctions.IFunc<String>() {
            public String Func() throws java.lang.Exception {
                return GetNextDeparturesWithDetails(crs, filterList, timeOffset, timeWindow, AccessToken);
            }
        }, "GetNextDeparturesWithDetails");
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    public String GetFastestDepartures(final String crs, final String filterList, final String timeOffset, final String timeWindow, final String AccessToken) throws java.lang.Exception {

        /*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    public android.os.AsyncTask<Void, Void, ALROperationResult<String>> GetFastestDeparturesAsync(final String crs, final String filterList, final String timeOffset, final String timeWindow, final String AccessToken) {
        return executeAsync(new ALRFunctions.IFunc<String>() {
            public String Func() throws java.lang.Exception {
                return GetFastestDepartures(crs, filterList, timeOffset, timeWindow, AccessToken);
            }
        }, "GetFastestDepartures");
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    public String GetFastestDeparturesWithDetails(final String crs, final String filterList, final String timeOffset, final String timeWindow, final String AccessToken) throws java.lang.Exception {

        /*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    public android.os.AsyncTask<Void, Void, ALROperationResult<String>> GetFastestDeparturesWithDetailsAsync(final String crs, final String filterList, final String timeOffset, final String timeWindow, final String AccessToken) {
        return executeAsync(new ALRFunctions.IFunc<String>() {
            public String Func() throws java.lang.Exception {
                return GetFastestDeparturesWithDetails(crs, filterList, timeOffset, timeWindow, AccessToken);
            }
        }, "GetFastestDeparturesWithDetails");
    }

    protected java.lang.Object execute(ALRIWcfMethod wcfMethod, String methodName, com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws java.lang.Exception {
        org.ksoap2.transport.Transport __httpTransport = createTransport();
        __httpTransport.debug = enableLogging;
        ALRExtendedSoapSerializationEnvelope __envelope = wcfMethod.CreateSoapEnvelope();
        try {
            sendRequest(methodName, __envelope, __httpTransport, profile);
        } finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump", __httpTransport.requestDump);

                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump", __httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault) {
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault) __retObj;
            throw convertToException(__fault, __envelope);
        } else {
            return wcfMethod.ProcessResult(__envelope, __retObj);
        }
    }

    protected <T> android.os.AsyncTask<Void, Void, ALROperationResult<T>> executeAsync(final ALRFunctions.IFunc<T> func, final String methodName) {
        return new android.os.AsyncTask<Void, Void, ALROperationResult<T>>() {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            }

            @Override
            protected ALROperationResult<T> doInBackground(Void... params) {
                ALROperationResult<T> result = new ALROperationResult<T>();
                try {
                    result.MethodName = methodName;
                    result.Result = func.Func();
                } catch (java.lang.Exception ex) {
                    ex.printStackTrace();
                    result.Exception = ex;
                }
                return result;
            }

            @Override
            protected void onPostExecute(ALROperationResult<T> result) {
                callback.Completed(result);
            }
        }.execute();
    }

    protected java.lang.Exception convertToException(org.ksoap2.SoapFault fault, ALRExtendedSoapSerializationEnvelope envelope) {
        org.ksoap2.SoapFault newException = fault;
        return newException;
    }

    interface ALRIWcfMethod {
        ALRExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(ALRExtendedSoapSerializationEnvelope __envelope, java.lang.Object result) throws java.lang.Exception;
    }
}


