package uk.co.suskins.darwin;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class ALRServiceItem extends ALRBaseServiceItem implements KvmSerializable {

    public ALRArrayOfServiceLocations origin;

    public ALRArrayOfServiceLocations destination;

    public ALRArrayOfServiceLocations currentOrigins;

    public ALRArrayOfServiceLocations currentDestinations;


    @Override
    public void loadFromSoap(java.lang.Object paramObj, ALRExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        super.loadFromSoap(paramObj, __envelope);


    }

    @Override
    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ALRExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("origin")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.origin = (ALRArrayOfServiceLocations) __envelope.get(j, ALRArrayOfServiceLocations.class, false);
            }
            return true;
        }
        if (info.name.equals("destination")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.destination = (ALRArrayOfServiceLocations) __envelope.get(j, ALRArrayOfServiceLocations.class, false);
            }
            return true;
        }
        if (info.name.equals("currentOrigins")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.currentOrigins = (ALRArrayOfServiceLocations) __envelope.get(j, ALRArrayOfServiceLocations.class, false);
            }
            return true;
        }
        if (info.name.equals("currentDestinations")) {
            if (obj != null) {
                java.lang.Object j = obj;
                this.currentDestinations = (ALRArrayOfServiceLocations) __envelope.get(j, ALRArrayOfServiceLocations.class, false);
            }
            return true;
        }
        return super.loadProperty(info, soapObject, __envelope);
    }


    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (propertyIndex == count + 0) {
            return this.origin != null ? this.origin : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == count + 1) {
            return this.destination != null ? this.destination : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == count + 2) {
            return this.currentOrigins != null ? this.currentOrigins : SoapPrimitive.NullSkip;
        }
        if (propertyIndex == count + 3) {
            return this.currentDestinations != null ? this.currentDestinations : SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount() + 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        int count = super.getPropertyCount();
        if (propertyIndex == count + 0) {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "origin";
            info.namespace = "http://thalesgroup.com/RTTI/2015-11-27/ldb/types";
        }
        if (propertyIndex == count + 1) {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "destination";
            info.namespace = "http://thalesgroup.com/RTTI/2015-11-27/ldb/types";
        }
        if (propertyIndex == count + 2) {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "currentOrigins";
            info.namespace = "http://thalesgroup.com/RTTI/2015-11-27/ldb/types";
        }
        if (propertyIndex == count + 3) {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "currentDestinations";
            info.namespace = "http://thalesgroup.com/RTTI/2015-11-27/ldb/types";
        }
        super.getPropertyInfo(propertyIndex, arg1, info);
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


}
