package uk.co.suskins.darwin;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.AttributeInfo;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class ALRToiletAvailabilityType {

    public String value;

    public ALREnums.ToiletStatus status;

    private transient java.lang.Object __source;


    public void loadFromSoap(java.lang.Object paramObj, ALRExtendedSoapSerializationEnvelope __envelope) {
        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;
        __source = inObj;
        if (!(inObj instanceof SoapObject)) {
            java.lang.Object j = inObj;
            value = j.toString();
        }

        if (inObj.hasAttribute("status")) {
            java.lang.Object j = inObj.getAttribute("status");
            if (j != null) {
                status = ALREnums.ToiletStatus.fromString(j.toString());
            }
        }

    }


    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ALRExtendedSoapSerializationEnvelope __envelope) {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("value")) {
            if (obj != null) {
                if (obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    if (j.toString() != null) {
                        this.value = j.toString();
                    }
                } else if (obj instanceof String) {
                    this.value = (String) obj;
                }
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource() {
        return __source;
    }

    public Object getSimpleValue() {
        Object value = this.value != null ? this.value : "";
        SoapPrimitive primitive = new SoapPrimitive("http://thalesgroup.com/RTTI/2017-10-01/ldb/commontypes", "value", value);

        if (this.status != null) {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("status");
            attrInfo.setValue(this.status);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        return primitive;
    }
}
